stages:
  - image-build
  - deploy

#job name    
image-build:
  stage: image-build
  image: docker:latest
  tags:
    - docker-executor
  before_script:
    - echo $CI_REGISTRY_USER
    - ls -lh; hostname; pwd
##    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login gitlab.bova-vp.ru:5050
  script:        
    - unset DOCKER_HOST
##    - docker build -t vpovetkin/myapp .
##    - docker push vpovetkin/myapp
    - docker build -t gitlab.bova-vp.ru:5050/root/myapp .
    - docker push gitlab.bova-vp.ru:5050/root/myapp
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "test"

deploy-dev:
  stage: deploy
  image:
    name: quay.io/appuio/oc:v4.12
    entrypoint: ['']
  before_script:
    - echo $IMAGE
  script:
    - 'curl --insecure --header "PRIVATE-TOKEN: $CONFIG_ACCESS_TOKEN" "$CI_API_V4_URL/projects/1/repository/files/deployment%2Eyml/raw?ref=main" > deployment.yml'
    - sed -i "s~{IMAGE}~$IMAGE~g" deployment.yml
    - cat deployment.yml

    - kubectl config use-context root/myapp:mydev
    - kubectl config get-contexts
    - kubectl get pods
    - kubectl apply -f deployment.yml -n mydev-ns
  rules:
      - if: $CI_COMMIT_BRANCH == "dev"
      - if: $CI_COMMIT_BRANCH == "main"
  tags:
      - docker-executor    